version: "3.8"
services:
  app:
    build: .
    container_name: wallet_app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

networks:
  default:
    driver: bridge